
import type { Character, Story } from './types';

export const mockCharacters: Character[] = [
  {
    id: '1',
    name: 'Jan van der Meer',
    age: '32',
    job: 'Softwareontwikkelaar',
    gender: 'Man',
    location: 'Utrecht',
    role: 'Protagonist',
    lengthM: '1',
    lengthCm: '85',
    build: 'Atletisch',
    hairColor: 'Bruin',
    hairStyle: 'Kort',
    eyes: 'Blauw',
    facialHair: 'Stoppelbaard',
    bodyHair: ['Borst: Licht', 'Armen: Gemiddeld'],
    impression: 'Zelfverzekerd',
    style: 'Casual',
    outfitTop: 'T-shirt',
    outfitBottom: 'Jeans',
    shoes: 'Sneakers',
    personality: 'Rustig en analytisch, met een droog gevoel voor humor. Wordt gedreven door logica en een verlangen om complexe problemen op te lossen. Kan soms wat introvert overkomen, maar is loyaal aan de mensen om wie hij geeft.',
    backstory: 'Opgegroeid in een klein dorp, verhuisde Jan naar de stad voor zijn studie en is daar blijven hangen. Hij heeft een fascinatie voor kunstmatige intelligentie en werkt aan een persoonlijk project dat de grenzen van technologie verkent.',
    imageUrl: '',
    imageHint: 'male portrait',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/50',
    iconTextClass: 'text-blue-700 dark:text-blue-300',
    description: `Jan van der Meer is een man die op het eerste gezicht rust en stabiliteit uitstraalt. Met zijn 32 jaar staat hij stevig in het leven, een indruk die wordt versterkt door zijn atletische lichaamsbouw en een lengte van 1.85 meter. Hij woont in de levendige stad Utrecht, waar hij werkt als een getalenteerde softwareontwikkelaar. Zijn uiterlijk is verzorgd maar zonder fratsen. Zijn donkerbruine haar is praktisch kort geknipt, en zijn helderblauwe ogen vormen een opvallend contrast. Meestal is zijn kaaklijn bedekt met een nette, korte stoppelbaard, wat hem een peinzende en geconcentreerde uitstraling geeft. Zijn lichaamsbeharing is bescheiden, met wat licht borsthaar en een gemiddelde hoeveelheid op zijn armen, passend bij zijn mannelijke maar verfijnde voorkomen.  Zijn kledingkeuze weerspiegelt zijn persoonlijkheid: functioneel, comfortabel en pretentieloos. Hij geeft de voorkeur aan een casual stijl, vaak bestaande uit een goed passend T-shirt, een comfortabele jeans en een paar moderne sneakers. Het is een outfit die hem bewegingsvrijheid geeft, of hij nu geconcentreerd achter zijn bureau zit of door de stad fietst.  De eerste indruk die Jan achterlaat is die van een zelfverzekerde, misschien zelfs ietwat serieuze man. Dit is echter slechts één kant van zijn karakter. Onder die kalme oppervlakte schuilt een scherpe, analytische geest met een verrassend droog gevoel voor humor. Hij wordt gedreven door een onstilbare intellectuele nieuwsgierigheid en een passie voor het oplossen van complexe problemen, wat hem een uitstekende softwareontwikkelaar maakt. Zijn fascinatie voor kunstmatige intelligentie gaat diep; in zijn vrije tijd werkt hij aan een persoonlijk project dat de grenzen van technologie en bewustzijn verkent.  Hoewel hij in sociale situaties soms als introvert kan worden bestempeld, is Jan een rots in de branding voor degenen die hij tot zijn vriendenkring rekent. Hij is buitengewoon loyaal en betrouwbaar. Zijn reis van een klein, rustig dorp naar de dynamische stad Utrecht heeft hem gevormd tot wie hij nu is: een man die het beste van twee werelden combineert. Hij is de onbetwiste protagonist van zijn eigen verhaal, een stille kracht die met logica en creativiteit zijn weg baant door de complexiteit van de moderne wereld.`
  },
  {
    id: '2',
    name: 'Eva de Wit',
    age: '28',
    job: 'Grafisch ontwerper',
    gender: 'Vrouw',
    location: 'Amsterdam',
    role: 'Ondersteunend personage',
    lengthM: '1',
    lengthCm: '70',
    build: 'Slank',
    hairColor: 'Blond',
    hairStyle: 'Lang',
    eyes: 'Groen',
    impression: 'Vriendelijk',
    features: ['Tatoeage op haar pols', 'Sproeten'],
    style: 'Elegant',
    outfitTop: 'Blouse',
    outfitBottom: 'Rok',
    shoes: 'Laarzen',
    breastsCup: 'B',
    breastsShape: 'Natuurlijk',
    buttocksSize: 'Gemiddeld',
    buttocksShape: 'Rond',
    lingerieMainType: 'Lingeriesetje',
    lingerieTopType: 'Bralette (zonder beugel)',
    lingerieBottomType: 'Hipster / Heupslip',
    lingerieStyle: 'Kant',
    lingerieMaterial: 'Kant',
    lingerieColor: 'Zwart',
    personality: 'Creatief, extravert en altijd op zoek naar inspiratie. Ze heeft een open en warme persoonlijkheid en maakt gemakkelijk contact met anderen. Ze is een dromer met een praktische inslag.',
    backstory: 'Eva groeide op in een artistieke familie en wist al op jonge leeftijd dat ze iets creatiefs wilde doen. Na de kunstacademie begon ze voor zichzelf als freelance grafisch ontwerper. Ze haalt haar inspiratie uit reizen en de bruisende cultuur van Amsterdam.',
    imageUrl: '', 
    imageHint: 'female portrait',
    iconBgClass: 'bg-pink-100 dark:bg-pink-900/50',
    iconTextClass: 'text-pink-700 dark:text-pink-300',
    description: `Eva de Wit is een levendige verschijning die de creatieve en dynamische sfeer van haar woonplaats Amsterdam perfect belichaamt. Als 28-jarige grafisch ontwerper heeft ze een pad voor zichzelf gecreëerd dat zowel artistiek als professioneel bevredigend is. Met haar 1.70 meter en slanke, elegante bouw beweegt ze zich met een natuurlijke gratie. Haar lange, blonde haar draagt ze meestal los, waardoor het vrij kan dansen in de wind terwijl ze door de straten fietst. Haar gezicht wordt gekenmerkt door een open en vriendelijke uitstraling, versterkt door haar stralende groene ogen en een lichte nevel van sproeten die over haar neus en wangen danst. Een klein, betekenisvol detail is de delicate tatoeage die haar pols siert, een permanent symbool van een persoonlijk verhaal. Eva’s kledingstijl is een naadloze mix van elegantie en comfort. Ze heeft een voorliefde voor vloeiende stoffen en doordachte combinaties, zoals een chique blouse ingestopt in een stijlvolle rok, vaak gecomplementeerd door een paar modieuze laarzen die zowel praktisch als verfijnd zijn. Haar figuur is vrouwelijk en in balans; ze heeft een natuurlijke B-cup en ronde, gemiddeld grote billen. Voor haar lingerie kiest ze vaak voor comfortabele maar sensuele setjes, zoals een zwarte kanten bralette met een bijpassende hipster, die haar een gevoel van zelfvertrouwen geven. In haar kern is Eva een extraverte en warme persoonlijkheid. Ze legt gemakkelijk contact en haar oprechte interesse in anderen maakt haar een geliefd persoon in haar sociale kring. Ze is een dromer met een praktische inslag; haar creatieve visies weet ze om te zetten in concrete en succesvolle projecten. Haar jeugd in een artistieke familie heeft haar de vrijheid en aanmoediging gegeven om haar passies te volgen. Na de kunstacademie koos ze bewust voor het freelance-bestaan, wat haar de flexibiliteit geeft om inspiratie op te doen uit reizen en de diverse culturele scene van Amsterdam. In het grotere verhaal fungeert Eva als een ondersteunend personage, maar ze is de onbetwiste regisseur van haar eigen leven, een bron van inspiratie en positiviteit voor de mensen om haar heen.`
  }
];

export const mockStories: Story[] = [];

    