import type { Character, Story } from './types';

export const mockCharacters: Character[] = [
  {
    id: '1',
    name: 'Jan van der Meer',
    age: '32',
    job: 'Softwareontwikkelaar',
    gender: 'Man',
    location: 'Utrecht',
    role: 'Protagonist',
    lengthM: '1',
    lengthCm: '85',
    build: 'Atletisch',
    hairColor: 'Bruin',
    hairStyle: 'Kort',
    eyes: 'Blauw',
    facialHair: 'Stoppelbaard',
    bodyHair: ['Borst: Licht', 'Armen: Gemiddeld'],
    impression: 'Zelfverzekerd',
    style: 'Casual',
    outfitTop: 'T-shirt',
    outfitBottom: 'Jeans',
    shoes: 'Sneakers',
    personality: 'Rustig en analytisch, met een droog gevoel voor humor. Wordt gedreven door logica en een verlangen om complexe problemen op te lossen. Kan soms wat introvert overkomen, maar is loyaal aan de mensen om wie hij geeft.',
    backstory: 'Opgegroeid in een klein dorp, verhuisde Jan naar de stad voor zijn studie en is daar blijven hangen. Hij heeft een fascinatie voor kunstmatige intelligentie en werkt aan een persoonlijk project dat de grenzen van technologie verkent.',
    imageUrl: '',
    imageHint: 'male portrait',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/50',
    iconTextClass: 'text-blue-700 dark:text-blue-300',
    description: 'Jan van der Meer, een 32-jarige softwareontwikkelaar uit Utrecht, is een man die rust en zelfverzekerdheid uitstraalt. Met een atletische bouw en een lengte van 1.85 meter heeft hij een krachtige aanwezigheid. Zijn korte, bruine haar en helderblauwe ogen geven hem een open en benaderbare blik, die wordt versterkt door een permanente, verzorgde stoppelbaard. Zijn kledingstijl is overwegend casual, meestal bestaande uit een goed passend T-shirt, een donkere jeans en moderne sneakers. Qua persoonlijkheid is Jan rustig en analytisch, met een scherp, droog gevoel voor humor dat hij alleen deelt met mensen die hij vertrouwt. Zijn logische denkwijze en passie voor het oplossen van complexe puzzels maken hem tot een gedreven ontwikkelaar. Hij groeide op in een klein dorp, maar vond zijn plek in de stad, waar hij nu werkt aan een grensverleggend AI-project. Ondanks zijn soms introverte aard is hij een zeer loyale vriend en de onbetwiste protagonist van zijn eigen verhaal.'
  },
  {
    id: '2',
    name: 'Eva de Wit',
    age: '28',
    job: 'Grafisch ontwerper',
    gender: 'Vrouw',
    location: 'Amsterdam',
    role: 'Ondersteunend personage',
    lengthM: '1',
    lengthCm: '70',
    build: 'Slank',
    hairColor: 'Blond',
    hairStyle: 'Lang',
    eyes: 'Groen',
    impression: 'Vriendelijk',
    features: ['Tatoeage op haar pols', 'Sproeten'],
    style: 'Elegant',
    outfitTop: 'Blouse',
    outfitBottom: 'Rok',
    shoes: 'Laarzen',
    breastsCup: 'B',
    breastsShape: 'Natuurlijk',
    buttocksSize: 'Gemiddeld',
    buttocksShape: 'Rond',
    lingerieMainType: 'Lingeriesetje',
    lingerieTopType: 'Bralette (zonder beugel)',
    lingerieBottomType: 'Hipster / Heupslip',
    lingerieStyle: 'Kant',
    lingerieMaterial: 'Kant',
    lingerieColor: 'Zwart',
    personality: 'Creatief, extravert en altijd op zoek naar inspiratie. Ze heeft een open en warme persoonlijkheid en maakt gemakkelijk contact met anderen. Ze is een dromer met een praktische inslag.',
    backstory: 'Eva groeide op in een artistieke familie en wist al op jonge leeftijd dat ze iets creatiefs wilde doen. Na de kunstacademie begon ze voor zichzelf als freelance grafisch ontwerper. Ze haalt haar inspiratie uit reizen en de bruisende cultuur van Amsterdam.',
    imageUrl: '', 
    imageHint: 'female portrait',
    iconBgClass: 'bg-pink-100 dark:bg-pink-900/50',
    iconTextClass: 'text-pink-700 dark:text-pink-300',
    description: "Eva de Wit is een 28-jarige, sprankelende grafisch ontwerper die de creatieve energie van haar woonplaats Amsterdam belichaamt. Met haar 1.70 meter en slanke bouw heeft ze een gracieuze verschijning. Haar lange, blonde haar valt vaak los over haar schouders en haar groene ogen stralen een vriendelijke en open warmte uit. Een subtiele tatoeage op haar pols en een lichte sprenkeling van sproetjes over haar neus geven haar een unieke, artistieke charme. Eva's kledingstijl is elegant en vrouwelijk; ze draagt graag een stijlvolle blouse op een zwierige rok, gecombineerd met leren laarzen. Onder haar kleding geeft ze de voorkeur aan comfortabele maar mooie lingerie, zoals een zwart kanten bralette-setje. Als persoon is Eva extravert en maakt ze moeiteloos contact, altijd op zoek naar inspiratie in de wereld om haar heen. Haar achtergrond in een artistieke familie heeft haar gevormd tot een creatieve dromer met een praktische inslag, die haar passie heeft omgezet in een succesvolle carrière als freelance ontwerper."
  }
];

export const mockStories: Story[] = [];
