import type { Character, Story } from './types';

export const mockCharacters: Character[] = [
  {
    id: '1',
    name: 'Jan van der Meer',
    age: '32',
    job: 'Softwareontwikkelaar',
    gender: 'Man',
    location: 'Utrecht',
    role: 'Protagonist',
    lengthM: '1',
    lengthCm: '85',
    build: 'Atletisch',
    hairColor: 'Bruin',
    hairStyle: 'Kort',
    eyes: 'Blauw',
    facialHair: 'Stoppelbaard',
    bodyHair: ['Borst: Licht', 'Armen: Gemiddeld'],
    impression: 'Zelfverzekerd',
    style: 'Casual',
    outfitTop: 'T-shirt',
    outfitBottom: 'Jeans',
    shoes: 'Sneakers',
    personality: 'Rustig en analytisch, met een droog gevoel voor humor. Wordt gedreven door logica en een verlangen om complexe problemen op te lossen. Kan soms wat introvert overkomen, maar is loyaal aan de mensen om wie hij geeft.',
    backstory: 'Opgegroeid in een klein dorp, verhuisde Jan naar de stad voor zijn studie en is daar blijven hangen. Hij heeft een fascinatie voor kunstmatige intelligentie en werkt aan een persoonlijk project dat de grenzen van technologie verkent.',
    imageUrl: '',
    imageHint: 'male portrait',
    iconBgClass: 'bg-blue-100 dark:bg-blue-900/50',
    iconTextClass: 'text-blue-700 dark:text-blue-300',
    description: 'Jan van der Meer is een 32-jarige softwareontwikkelaar uit Utrecht. Met een lengte van 1,85 m en een atletische bouw heeft hij een zelfverzekerde uitstraling. Zijn korte, bruine haar en blauwe ogen worden gecomplementeerd door een permanente stoppelbaard. Meestal is hij casual gekleed in een t-shirt en jeans met sneakers. Zijn rustige en analytische persoonlijkheid verbergt een scherpe, droge humor. Hij is een loyale vriend, gedreven door logica en een passie voor het oplossen van complexe problemen. In zijn vrije tijd werkt hij aan een geavanceerd AI-project, een passie die voortkomt uit zijn jeugd in een klein dorp en zijn fascinatie voor de grenzen van technologie.'
  },
  {
    id: '2',
    name: 'Eva de Wit',
    age: '28',
    job: 'Grafisch ontwerper',
    gender: 'Vrouw',
    location: 'Amsterdam',
    role: 'Ondersteunend personage',
    lengthM: '1',
    lengthCm: '70',
    build: 'Slank',
    hairColor: 'Blond',
    hairStyle: 'Lang',
    eyes: 'Groen',
    impression: 'Vriendelijk',
    features: ['Tatoeage op haar pols', 'Sproeten'],
    style: 'Elegant',
    outfitTop: 'Blouse',
    outfitBottom: 'Rok',
    shoes: 'Laarzen',
    breastsCup: 'B',
    breastsShape: 'Natuurlijk',
    buttocksSize: 'Gemiddeld',
    buttocksShape: 'Rond',
    lingerieStyle: 'Kant',
    lingerieColor: 'Zwart',
    personality: 'Creatief, extravert en altijd op zoek naar inspiratie. Ze heeft een open en warme persoonlijkheid en maakt gemakkelijk contact met anderen. Ze is een dromer met een praktische inslag.',
    backstory: 'Eva groeide op in een artistieke familie en wist al op jonge leeftijd dat ze iets creatiefs wilde doen. Na de kunstacademie begon ze voor zichzelf als freelance grafisch ontwerper. Ze haalt haar inspiratie uit reizen en de bruisende cultuur van Amsterdam.',
    imageUrl: '', 
    imageHint: 'female portrait',
    iconBgClass: 'bg-pink-100 dark:bg-pink-900/50',
    iconTextClass: 'text-pink-700 dark:text-pink-300',
    description: 'Eva de Wit is een 28-jarige, creatieve en energieke grafisch ontwerper uit Amsterdam. Ze is 1,70 m lang met een slanke bouw, lang blond haar en opvallende groene ogen. Haar vriendelijke en open persoonlijkheid wordt weerspiegeld in haar elegante kledingstijl, vaak een combinatie van een blouse, rok en laarzen. Ze heeft een discrete tatoeage op haar pols en een paar charmante sproeten. Eva is een extraverte dromer die gemakkelijk contact maakt. Haar passie voor kunst en design, gevoed door haar artistieke familie en reizen, is de kern van haar werk en leven.'
  }
];

export const mockStories: Story[] = [];
